### ISSUE TITLE
Understanding runtimes of different models

### ISSUE THREAD

**Issue by gerardb7** [awslabs/mlm-scoring#3]
Hi,

I need to score a rather large number of sentences for a downstream task. I'm experimenting with models supported by huggingface with no fine tuning, e.g.: 

```    ctxs = [mx.gpu(0)]
    mlms_model, vocab, tokenizer = get_pretrained(ctxs, 'albert-base-v2')
    scorer = MLMScorerPT(mlms_model, vocab, tokenizer, ctxs)
    sentences = ... # 1847 sentences
    corpus = Corpus.from_text(sentences)
    scores = self.scorer.score(corpus, 1.0, 500) # adjusted batch size to avoid gpu out of memory errors
```

Depending on the model and scorer I get wildly different runtimes. On my computer, encoding 1847 sentences:

- MXNet MLMs like 'bert-base-en-cased' and  'roberta-base-en-cased' with MLMScorer take 3-4 minutes
-  MXNet LMs like 'gpt2-117m-en-cased' with LMScorer take about 8-10 secs (for some reason I need to lower the batch size to around 50)
- 'albert-base-v1' and 'albert-base-v2' with MLMScorerPT take 4-5 minutes. 
- 'distilbert-base-cased' and 'distilbert-base-uncased' take 1-2 minutes.

I expected, perhaps naively, that ALBERT and DistilBERT would be much faster due to reduced dimensionality and number of layers.

**Comment by JulianSlzr** [comment]
Hi Gerard,

These numbers make sense.
- LM vs MLM is due to 1 copy vs. L parallel copies. Look at our maskless finetuning to mitigate this; or perhaps unmasked scores might suit your needs (e.g., this new paper: https://arxiv.org/abs/2010.09535)
- While ALBERT has fewer _unique_ parameters, inference still passes sequentially through 12 layers (plus the factorized embedding, which breaks one computation into two). PyTorch models are also slower right now since we go via MXNet's dataloader. **Did you try increasing the batch size? You should be able to load more as the model is smaller.**
- DistilBERT's inference speed is in line with the 40% reduction from their paper (Table 3: https://arxiv.org/pdf/1910.01108.pdf). **You could also increase the batch size here.**

Hope this helps!
